- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install Flatpak packages
      ansible.builtin.flatpak:
        name:
          - com.brave.Browser
          - com.spotify.Client
          - com.jetbrains.IntelliJ-IDEA-Ultimate
          - org.wezfurlong.wezterm
          - net.kuribo64.melonDS
          - com.mattjakeman.ExtensionManager
          - es.danirod.Cartero
          - com.google.AndroidStudio
          - com.valvesoftware.Steam
          - com.jetbrains.DataGrip
          - com.getpostman.Postman
        state: present

    - name: Install DNF packages
      ansible.builtin.dnf:
        name:
          - gnome-tweaks
          - vlc
          - alacritty
          - htop
          - papirus-icon-theme
          - fastfetch
          - neovim
          - bat
          - jetbrains-mono-fonts-all
          - cascadia-fonts-all
          - gparted
          - pip
          - fzf
          - maven
          - sassc
          - libvirt
          - bleachbit
         # - obs
        state: present

    - name: Install Group packages
      ansible.builtin.dnf:
        name: 
          - "@Multimedia"
          - "@Development Tools"
        state: present

    - name: Remove unwanted GNOME software
      ansible.builtin.dnf:
        name:
          - gnome-tour
          - totem
          - mediawriter
          - yelp
          - gnome-contacts
          - rhythmbox
          - firefox 
          - anaconda-webui
          # - gnome-boxes
        state: absent
        autoremove: true