- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install Flatpak packages
      ansible.builtin.flatpak:
        name:
          - com.brave.Browser
          - es.danirod.Cartero
          - com.getpostman.Postman
          # - com.google.AndroidStudio
          - com.jetbrains.DataGrip
          - com.jetbrains.IntelliJ-IDEA-Ultimate
          - com.mattjakeman.ExtensionManager
          # - net.kuribo64.melonDS
          - com.obsproject.Studio
          - com.spotify.Client
          - com.valvesoftware.Steam
        remote: flathub
        state: present

    - name: Install DNF packages
      ansible.builtin.dnf:
        name:
          - alacritty
          - bat
          - bleachbit
          - cascadia-fonts-all
          - fastfetch
          - fzf
          - gnome-tweaks
          - gparted
          - htop
          - jetbrains-mono-fonts-all
          - libvirt
          - maven
          - neovim
          - papirus-icon-theme
          - pip
          - sassc
          - vlc
        state: present

    - name: Install Group packages
      ansible.builtin.dnf:
        name: 
          - "@Multimedia"
          - "@Development Tools"
        state: present

    - name: Remove unwanted GNOME software
      ansible.builtin.dnf:
        name:
          - gnome-tour
          - totem
          - mediawriter
          - yelp
          - gnome-contacts
          - rhythmbox
          - firefox 
          - anaconda-webui
        state: absent
        autoremove: true