- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Asegurarse de que el módulo community.general esté instalado
      ansible.builtin.import_role:
        name: community.general.dnf_config_manager

    - name: Install RPM Fusion Free and Non-Free Repositories
      command: >
        dnf install -y
        https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
        https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
        
    - name: Deshabilitar repositorios específicos
      community.general.dnf_config_manager:
        name:
          - google-chrome
          - copr:copr.fedorainfracloud.org:phracek:PyCharm
          - rpmfusion-nonfree-nvidia-driver
          - rpmfusion-nonfree-steam
        state: disabled

    - name: Configure dnf
      lineinfile:
        path: /etc/dnf/dnf.conf
        line: "max_parallel_downloads=10"
        create: yes

    - name: Install Git & Zsh
      dnf:
        name: 
          - git
          - zsh
        state: present
        
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install Oh-My-Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
      args:
        creates: ~/.oh-my-zsh
      become: false
