- hosts: localhost
  connection: local
  become: true
  
  tasks:
    - name: Install RPM Fusion Free and Non-Free Repositories
      ansible.builtin.dnf:
        name:
          - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
          - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    ## Wait for fedora 41 compatibility    
    # - name: Disable unused repositories
    #   community.general.dnf_config_manager:
    #     name:
    #       - google-chrome
    #       - copr:copr.fedorainfracloud.org:phracek:PyCharm
    #       - rpmfusion-nonfree-nvidia-driver
    #       - rpmfusion-nonfree-steam
    #     state: disabled

    - name: Configure dnf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        line: "max_parallel_downloads=10"
        create: true
        state: present

    - name: Install basic programs
      ansible.builtin.dnf:
        name: 
          - git
          - zsh
        state: present

    - name: Update all packages
      ansible.builtin.dnf5:
        name: "*"
        state: latest

    # - name: Set Zsh as default shell
    #   ansible.builtin.user:
    #       name: "{{ ansible_env.USER }}"
    #       shell: /bin/zsh
    # become: false

