- hosts: localhost
  connection: local

  vars_prompt:
    - name: "email"
      prompt: "Please enter your email for the SSH key"
      private: no
 
  tasks:
    - name: Add Zellij auto-start to .zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'eval "$(zellij setup --generate-auto-start zsh)"'
        create: yes
        
    - name: Agregar fzf al archivo .zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'source <(fzf --zsh)'
        create: yes
        
    - name: Create .ssh directory in home
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0755"

    - name: Generate SSH key
      command: ssh-keygen -t ed25519 -C "{{ email }}" -f "{{ ansible_env.HOME }}/.ssh/id_ed25519" -N ""
      args:
        creates: "{{ ansible_env.HOME }}/.ssh/id_ed25519"

    - name: Start SSH agent
      shell: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519
