- hosts: localhost
  connection: local

  tasks:
    - name: Root tasks
      block:
        - name: Import Microsoft GPG key
          ansible.builtin.rpm_key:
            state: present
            key: https://packages.microsoft.com/keys/microsoft.asc

        - name: Add Visual Studio Code repository
          ansible.builtin.copy:
            dest: /etc/yum.repos.d/vscode.repo
            content: |
              [code]
              name=Visual Studio Code
              baseurl=https://packages.microsoft.com/yumrepos/vscode
              enabled=1
              gpgcheck=1
              gpgkey=https://packages.microsoft.com/keys/microsoft.asc

        - name: Update DNF cache
          ansible.builtin.dnf5:
            update_cache: true

        - name: Install Visual Studio Code
          ansible.builtin.dnf5:
            name: code
            state: present

        - name: Enable Zellij COPR repository
          community.general.copr:
            host: copr.fedorainfracloud.org
            state: enabled
            name: varlad/zellij
          register: enable_copr
          changed_when: enable_copr.changed

        - name: Install Zellij
          ansible.builtin.dnf5:
            name: zellij
            state: present
          when: enable_copr.changed
      become: true

    - name: No root tasks
      block:
        - name: Add Zellij auto-start and fzf keybinds to .zshrc
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.zshrc"
            line: "{{ item }}"
            create: true
            state: present
          loop:
            - 'eval "$(zellij setup --generate-auto-start zsh)"'
            - 'source <(fzf --zsh)'

        - name: Check if Papirus Folders are installed
          ansible.builtin.stat:
            path: /usr/bin/papirus-folders
          register: papirus_folders_installed

        - name: Download Papirus Folders install script
          ansible.builtin.get_url:
            url: https://git.io/papirus-folders-install
            dest: /tmp/papirus-folders-install.sh
            mode: '0755'
          when: not papirus_folders_installed.stat.exists

        - name: Install Papirus Folders if not installed
          ansible.builtin.command: /tmp/papirus-folders-install.sh
          when: not papirus_folders_installed.stat.exists

        - name: Set Papirus Folders theme to bluegrey
          ansible.builtin.command: papirus-folders -C bluegrey --theme Papirus
      become: false