- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Import Microsoft GPG key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Visual Studio Code repository
      copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc

    - name: Update DNF cache
      command: dnf check-update

    - name: Install Visual Studio Code
      dnf:
        name: code
        state: present

    - name: Enable Zellij COPR repository
      command: dnf copr enable varlad/zellij -y
      register: enable_copr
      changed_when: enable_copr.rc == 0

    - name: Install Zellij
      dnf:
        name: zellij
        state: present
      register: install_zellij
      when: enable_copr is succeeded

    - name: Add Zellij auto-start to .zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'eval "$(zellij setup --generate-auto-start zsh)"'
        create: yes
      become: false

    - name: Agregar fzf al archivo .zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'source <(fzf --zsh)'
        create: yes
      become: false

    - name: Install Papirus Folders
      shell: wget -qO- https://git.io/papirus-folders-install | sh

    - name: Change Papirus Folder Color
      shell: papirus-folders -C bluegrey --theme Papirus
