- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Import Microsoft GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Visual Studio Code repository
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc

    - name: Update DNF cache and install Visual Studio Code
      ansible.builtin.dnf:
        update_cache: true
        name: code
        state: present

    - name: Enable Zellij COPR repository
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: varlad/zellij
      register: enable_zellij_copr
      changed_when: enable_zellij_copr.changed

    - name: Install Zellij
      ansible.builtin.dnf:
        name: zellij
        state: present
      when: enable_zellij_copr.changed

    - name: Enable Eza COPR repository
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: alternateved/eza
      register: enable_eza_copr
      changed_when: enable_eza_copr.changed

    - name: Install Eza
      ansible.builtin.dnf:
        name: eza
        state: present
      when: enable_eza_copr.changed
      
    # - name: Check if Bun is installed
    #   ansible.builtin.command: which bun
    #   register: bun_installed
    #   ignore_errors: true
    #   become: false

    # - name: Install Bun using curl
    #   ansible.builtin.shell: curl -fsSL https://bun.sh/install | bash
    #   when: bun_installed.rc != 0
    #   become: false

    # - name: Check if Angular CLI is installed
    #   ansible.builtin.command: which ng
    #   register: angular_cli_installed
    #   ignore_errors: true
    #   become: false

    # - name: Install Angular CLI globally using Bun
    #   ansible.builtin.command: bun i -g @angular/cli
    #   when: angular_cli_installed.rc != 0
    #   become: false