- hosts: localhost
  connection: local

  tasks:
    - name: Start Docker service
      ansible.builtin.systemd_service:
        name: docker
        state: started
      become: true

    - name: Pull multiple Docker images
      community.docker.docker_image_pull:
        name: "{{ item }}"
      loop:
        - postgres
        - mysql
        - sonarqube
        - alpine
      become: false

    - name: Build Docker image from Dockerfile
      community.docker.docker_image_build:
        name: streamrip
        path: "{{ ansible_env.HOME }}/Music/Docker Image"
        dockerfile: Dockerfile
      become: false