- hosts: localhost
  connection: local
  become: true
  
  vars_prompt:
    - name: target_user
      prompt: "Add user name for docker group"
      private: false
      
  tasks:
    - name: Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
    # Wait for fedora 41  compatibility
    # - name: Add Docker repository
    #   ansible.builtin.command:
    #     cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    #     creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Create Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ target_user }}"
        groups: docker
        append: true