- hosts: localhost

  vars:
    projects_dir: ~/Documents/Projects
    dotfiles_repo: "{{ projects_dir }}/dotfiles"
    config: ~/.config

  tasks:
    - name: Crear directorio para proyectos
      file:
        path: "{{ projects_dir }}"
        state: directory

    - name: Clonar el repositorio de dotfiles
      git:
        repo: git@github.com:Adra642/dotfiles.git
        dest: "{{ dotfiles_repo }}"

    - name: Crear directorios necesarios en config
      file:
        path: "{{ config }}/{{ item }}"
        state: directory
      loop:
        - wezterm
        - zellij
        
    - name: Crear directorios necesarios en zellij
      file:
        path: "{{ config }}/zellij/{{ item }}"
        state: directory
      loop:
        - layouts
        - plugins
        - theme
        
    - name: Crear enlaces simbólicos para wezterm
      file:
        src: "{{ dotfiles_repo }}/wezterm/{{ item }}"
        dest: "{{ config }}/wezterm/{{ item }}"
        state: link
      loop:
        - wezterm.lua
        - color.lua
        
    - name: Crear enlace simbólico para zellij
      file:
        src: "{{ dotfiles_repo }}/{{ item }}"
        dest: "{{ config }}/{{ item }}"
        state: link
      loop:
        - zellij/config.kdl
        - zellij/layouts/work.kdl
        - zellij/theme/scheme.kdl

    - name: Descargar zjstatus.wasm en plugins
      get_url:
        url: https://github.com/dj95/zjstatus/releases/download/v0.17.0/zjstatus.wasm
        dest: "{{ config }}/zellij/plugins/zjstatus.wasm"

    - name: Crear directorio alacritty
      file:
        path: "{{ config }}/alacritty"
        state: directory

    - name: Crear enlace simbólico para alacritty.toml
      file:
        src: "{{ dotfiles_repo }}/alacritty/alacritty.toml"
        dest: "{{ config }}/alacritty/alacritty.toml"
        state: link

    - name: Crear directorio color_selector
      file:
        path: "{{ config }}/color_selector"
        state: directory

    - name: Crear enlaces simbólicos para color_selector
      file:
        src: "{{ dotfiles_repo }}/color_selector/{{ item }}"
        dest: "{{ config }}/color_selector/{{ item }}"
        state: link
      loop:
        - color_schemes.toml
        - alacritty_color.py
        - color_scheme_selector.py
        - wezterm_color.py
        - zellij_color.py
        
    - name: Crear enlace simbólico para adra.zsh-theme en temas de Oh My Zsh
      file:
        src: "{{ dotfiles_repo }}/zsh/adra.zsh-theme"
        dest: ~/.oh-my-zsh/custom/themes/adra.zsh-theme
        state: link

    - name: Clonar zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ lookup('env', 'ZSH') | default('~/.oh-my-zsh') }}/custom/plugins/zsh-autosuggestions"

    - name: Clonar zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ lookup('env', 'ZSH') | default('~/.oh-my-zsh') }}/custom/plugins/zsh-syntax-highlighting"

    - name: Instalar toml usando pip
      pip:
        name: toml
