- hosts: localhost
  connection: local

  vars_prompt:
    - name: user_email
      prompt: "Please enter your email for Git and SSH key"
      private: false

    - name: user_name
      prompt: "Please enter your name for Git"
      private: false

  tasks:
    - name: Set Git user configuration
      community.general.git_config:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - { key: "user.email", value: "{{ user_email }}" }
        - { key: "user.name", value: "{{ user_name }}" }

    - name: Create .ssh directory in home
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0700"

    - name: Generate SSH key
      ansible.builtin.command:
        cmd: ssh-keygen -t ed25519 -C "{{ user_email }}" -f "{{ ansible_env.HOME }}/.ssh/id_ed25519" -N ""
      args:
        creates: "{{ ansible_env.HOME }}/.ssh/id_ed25519"

    - name: Start SSH agent
      ansible.builtin.shell: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519
      args:
        executable: /bin/bash