- hosts: localhost
  connection: local

  vars_prompt:
    - name: user_email
      prompt: "Please enter your email for Git and SSH key"
      private: false

    - name: user_name
      prompt: "Please enter your name for Git"
      private: false

  tasks:
    - name: Set Git user configuration
      community.general.git_config:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - { key: "user.email", value: "{{ user_email }}" }
        - { key: "user.name", value: "{{ user_name }}" }

    - name: Create .ssh directory in home
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0700"

    - name: Generate an OpenSSH keypair using ed25519
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_ed25519_github"
        comment: "{{ user_email }}"
        type: ed25519
        mode: '0600'
        state: present
      register: ssh_key

    - name: Start SSH agent
      ansible.builtin.shell: |
        eval "$(ssh-agent -s)"
        ssh-add {{ ansible_env.HOME }}/.ssh/id_ed25519_github
      args:
        executable: /bin/bash
      when: ssh_key.changed