- hosts: localhost
  connection: local
 
  tasks:
    - name: Cambiar el tema a oscuro
      command: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

    - name: Configurar teclado a latinoamericano
      command: gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'latam')]"
    
    - name: Crear un atajo de teclado para abrir WezTerm
      command: |
        gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"    
    - name: Establecer el comando para el atajo WezTerm
      command: |
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'WezTerm'    
    
    - name: Establecer el comando del atajo WezTerm
      command: |
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'flatpak run org.wezfurlong.wezterm'
    
    - name: Establecer la combinación de teclas para WezTerm
      command: |
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Control><Alt>t'