- hosts: localhost
  connection: local

  vars_prompt:
    - name: user_email
      prompt: "Please enter your email for Git and SSH key"
      private: no
      
    - name: user_name
      prompt: "Please enter your name for Git"
      private: no

  tasks:
    - name: Set Git user email
      command: git config --global user.email "{{ user_email }}"
    
    - name: Set Git user name
      command: git config --global user.name "{{ user_name }}"