---
- name: Install Fedora packages and Flatpak applications
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install Flatpak packages
      community.general.flatpak:
        name:
          - com.brave.Browser
          - com.discordapp.Discord
          - com.github.tchx84.Flatseal
          # - com.google.AndroidStudio
          - com.jetbrains.DataGrip
          - com.jetbrains.IntelliJ-IDEA-Ultimate
          - com.mattjakeman.ExtensionManager
          - com.spotify.Client
          - com.usebottles.bottles
          - com.usebruno.Bruno
          - com.valvesoftware.Steam
          # - net.kuribo64.melonDS
          - net.lrclib.lrcge
          - org.eclipse.Java
          - org.inkscape.Inkscape
          - org.jellyfin.JellyfinDesktop
        remote: flathub
        state: present

    - name: Install DNF packages
      ansible.builtin.dnf:
        name:
          - alacritty
          - bat
          - bleachbit
          - cascadia-fonts-all
          - fastfetch
          - fzf
          - gnome-tweaks
          - gparted
          - htop
          - ibm-plex-fonts-all
          - jetbrains-mono-fonts-all
          - libvirt
          - maven
          - mpv
          - neovim
          - obs-studio
          - python3-pip
          - quodlibet
          - sassc
          - steam-devices
          - vlc
          - wireguard-tools
        state: present

    - name: Install package groups
      ansible.builtin.dnf:
        name:
          - "@Multimedia"
          - "@Development Tools"
        state: present

    - name: Remove unwanted GNOME software
      ansible.builtin.dnf:
        name:
          - anaconda-live
          - anaconda-webui
          - decibels
          - gnome-contacts
          - gnome-tour
          - mediawriter
          - showtime
          - yelp
        state: absent
        autoremove: true
