---
- name: Configure Fedora system with RPM Fusion and basic packages
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install RPM Fusion Free and Non-Free Repositories
      ansible.builtin.dnf:
        name:
          - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
          - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: Disable unused repositories
      ansible.builtin.command: dnf config-manager setopt {{ item }}.enabled=0
      loop:
        - google-chrome
        - copr:copr.fedorainfracloud.org:phracek:PyCharm
        - rpmfusion-nonfree-nvidia-driver
        - rpmfusion-nonfree-steam

    - name: Configure dnf parallel downloads
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        line: "max_parallel_downloads=10"
        create: true
        mode: "0644"
        state: present

    - name: Install basic programs
      ansible.builtin.dnf:
        name:
          - zsh
        state: present

    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
